version: '3'

services:
  healthchecks:
    image: quay.io/galexrt/healthchecks:v2.0.1
    restart: always
    ports:
      - "8000:8000"
    # Remove the brackets and uncomment the `SQLite` volumes entry
    volumes: []
      #- SQLite:/data
    environment:
      # Database config
      # For more information see https://github.com/galexrt/container-healthchecks/blob/main/README.md#database-configuration
      DB: "mysql"
      DB_HOST: ""
      DB_PORT: "3306"
      DB_NAME: "healthchecks"
      DB_USER: "healthchecks"
      DB_PASSWORD: "9tjgMCf0Ha0ZNyZwcUe9XzYG"
      # Healthchecks app config
      SECRET_KEY: "blablabla123"
      ALLOWED_HOSTS: 'localhost,healthchecks.example.com'
      DEBUG: "False"
      DEFAULT_FROM_EMAIL: "noreply@hc.example.com"
      USE_PAYMENTS: "False"
      REGISTRATION_OPEN: "False"
      EMAIL_HOST: ""
      EMAIL_PORT: "587"
      EMAIL_HOST_USER: ""
      EMAIL_HOST_PASSWORD: ""
      EMAIL_USE_TLS: "True"
      SITE_ROOT: "https://hc.example.com"
      SITE_NAME: "Mychecks"
      MASTER_BADGE_LABEL: "Mychecks"
      PING_ENDPOINT: "https://hc.example.com/ping/"
      PING_EMAIL_DOMAIN: "hc.example.com"
      # Healthchecks integration config
      TWILIO_ACCOUNT: "None"
      TWILIO_AUTH: "None"
      TWILIO_FROM: "None"
      PD_VENDOR_KEY: "None"
      TRELLO_APP_KEY: "None"
      CONTAINER_PRUNE_INTERVAL: 600
    # Comment the `links` and `depends_on` out if you want to use SQLite instead of mysql
    links:
      - mysql
    depends_on:
      - mysql
  # MySQL MariaDB databse server
  mysql:
    image: mariadb:10.7
    restart: always
    environment:
      MYSQL_DATABASE: 'healthchecks'
      # If you change the mysql user/password, you must update the `healthchecks` container
      # mysql credentials as well
      MYSQL_USER: 'healthchecks'
      MYSQL_PASSWORD: '9tjgMCf0Ha0ZNyZwcUe9XzYG'
    # Where our data will be persisted
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
  # If you want to use SQLite instead of MySQL, uncomment the `SQLite` lines
  #SQLite:
