name: build
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: galexrt
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Quay.io Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_QUAYIO_USERNAME }}
          password: ${{ secrets.REGISTRY_QUAYIO_PASSWORD }}
      - name: Build Container Image
        run: |
          make container-build VERSION="testbuild-pr"
